#!/bin/bash
# Made from scratch by Gibraan Jafar

# Make big file from the shell using crunch
# Compress it using tar in te=he same folder
# Uncompress it in root folder

read -p " Enter file to be compressed : " filename

if [ -z $filename ]
then
        echo " Enter something ! "
elif [ -e $filename ]
then
        tar -czvf $filename.gz $filename 
else
        echo " $filename does not exist "
fi

echo " Now , uncompressing it root folder "
tar -xzvf $filename.gz  -C ~/

# Interesting fact
# Can give the compressed file any extension . It could be .GaandMaraChutiye.Whatever
