#!/bin/bash
# Made from scratch by Gibraan Jafar

# Write a script to create an alias
# For example , here we are making nanol become alias for "nano -l"


echo "alias nanol='nano -l'" >> ~/.bashrc

# In terminal type => unalias nanol
