#!/bin/bash
# Made from scratch by Gibraan Jafar

# create a directory . Create 3 files in it with some content . Copy the entire folder
#        to another location . Delete original folder .

mkdir test
touch test/file1 test/file2
echo  Welcome to CyberCell ! > test/file1
echo  Are you ready ? ?        > test/file2
echo  Lets break some stuff ! > test/file3

cp -rf  test /home/el1t3/Downloads
rm -rf  test
echo Done !
