#!/bin/bash
# Made from scratch by Gibraan Jafar

# Create an html document and launch it using firefox 

echo " Creating an HTML document ... "

echo "<!DOCTYPE html>" > test.html
echo "<HTML>" >> test.html

echo -e "<TITLE> Sup ? </TITLE> " >> test.html
echo -e "<BODY>  \n This is for testing purposes \n </BODY>" >> test.html
echo -e	"</HTML>" >> test.html

sleep 5

echo "Launching web-page using firefox..."
firefox test.html
