#!/bin/bash

# Made from scratch by Gibraan Jafar

#PROBLEM STATEMENT
# Write a shell script to :
# unmount a USB
# mount it in Downloads folder
# Print contents of USB
# Put script to sleep for 30 seconds
# unmount the USB and eject it

# This program is pretty self explainatory .
# So no comments have been included.
# For more info check out man pages of umount and eject command

echo Umounting from /media/el1t3/GIB4B/
sudo umount /dev/sdb1
echo Mounting at /home/el1t3/Documents/VIIT/ForUSB
sudo mount /dev/sdb1 /home/el1t3/Documents/VIIT/ForUSB

echo Contents of USB :
ls /home/el1t3/Documents/VIIT/ForUSB

echo Shell script going into sleep for 30 seconds
echo Go into Documents or open another terminal to verify ..
sleep 30


echo Unmount sequence starting...
sudo umount /dev/sdb1
echo Ejecting USB ...
sudo eject /dev/sdb1
echo You may now remove your USB ... Thank you
