#!/bin/bash
# Made from scratch by Gibraan Jafar

# Print hostname , username , current working directory , current time (12hr_format:minute) .

echo Hostname of this device  : $HOSTNAME
echo User logged in right now :`whoami`
echo Current time	      : $(date +%I) : $(date +%M)

location=$PWD
echo Currently in $location/$0
