#!/bin/bash

# Made from scratch by Gibraan Jafar

read -p " Enter number of digits : " digits
pi $digits

# SCOPE FOR IMPOVEMENT
# Handle scenario when user presses enter
# without entering anything or enters negative value
