#!/bin/bash
# Made from scratch by Gibraan Jafar

# Print pattern of
#        *
#        **
#        ***


i=1
while [ $i -le 3 ]
do
	j=1
	while [ $j -le $i ]
	do
		echo -n  \*
		((j++))
	done
	echo
	((i++))
done


# TRY
# Print the pattern for as many rows
# as given by the user
