#!/bin/bash

# Made from scratch by Gibraan Jafar

# WSS to accept file name as argument . Check and print whether it is has Read and/or Write
#    and/or Execute permission.
#	Use If-Eles

echo -n "$1    :   "

if [ -r $1 ]
then
	echo -n "Read "
fi

if [ -w $1 ]
then
	echo -n ", Write "
fi

if [ -x $1 ]
then
	echo -n ", Execute "
fi

echo permissions

# Interesting fact :
# -r , -w , -x only check owner part of the entire permission
