#!/bin/bash
# Made from scratch by Gibraan Jafar

# Accept 2 values as arguments
# Display options
#	Press 1 to add
#	Press 2 to subtract
#	Enter your choice :
# And accordingly print result

echo -en " Press 1 to add  \n Press 2 to subtract \n Enter your choice : "
read choice

if [ "$choice" = "1" ]
then
	answer=$( expr $1 + $2 )
elif [ "$choice" = "2" ]
then
	 answer=$( expr $1 - $2 )
else
	echo " Sorry , that's all that I can do !"
	exit 1
fi

	echo " Result = $answer "
